version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: sop_django
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sop_django
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306

volumes:
  mysql_data: