# Generated by Django 4.2.19 on 2025-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobileNumber', models.CharField(default='', max_length=50)),
                ('specialization', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_physician',
            },
        ),
    ]
