# Generated by Django 4.2.19 on 2025-04-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_physician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Physician',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
