# Generated by Django 4.2.19 on 2025-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_delete_physician_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_physician',
            },
        ),
    ]
