# Generated by Django 4.2.19 on 2025-04-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_physician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Physician',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
