# Generated by Django 4.2.19 on 2025-04-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
