# Generated by Django 4.2.19 on 2025-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('appointmentDate', models.DateField()),
                ('contactNumber', models.CharField(max_length=50)),
                ('illness', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_client',
            },
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
