# Generated by Django 4.2.19 on 2025-04-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_client_delete_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
