# Generated by Django 4.2.19 on 2025-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('joiningDate', models.DateField()),
                ('division', models.CharField(max_length=50)),
                ('previousEmployer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_staff',
            },
        ),
    ]
