# Generated by Django 4.2.19 on 2025-04-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='previousEmployer',
        ),
    ]
